### ISSUE TITLE
Macros definition is broken

### ISSUE THREAD

**Issue by alex-bender** [goretk/redress#15]
Hello, thanks for such a great tool!
I've got across blog post and found out that probably syntax has changed so it's not working anymore with `r2 -v radare2 5.4.3`.
```
[0x00528b00]> (type+ flag,#!pipe redress -method -type `f~$0~[0]`)
Invalid macro body
```
If you would be able to take a loot at that it would be really great, thanks!

**Comment by TcM1911** [comment]
Yes r2 changed the syntax. I have something like this in my radare2rc file: `"(type+ flag;#!pipe redress -method -type `f~$0~[0]`;)"`

**Comment by alex-bender** [comment]
Thanks a lot!
